### PR TITLE
Remove Feature module to match setuptools >=46.0.0

### PR DESCRIPTION
**Pull request by userkkw**
https://github.com/pypa/setuptools/issues/65
https://github.com/pypa/setuptools/issues/2017
https://github.com/openslide/openslide/issues/287

untested

### CODE REVIEW

**Comment by rosbo** [comment]
This works for me.

I tested in a simple docker container. Here is the `Dockerfile`.

```
FROM continuumio/anaconda3:2019.03

RUN apt-get update && \
    apt-get install -y build-essential && \
    pip install pip==19.0.3 setuptools==46.1.3

ADD . openslide-python

RUN cd openslide-python && \
    pip install .
``` 

I then ran:

```
cd openslide-python
docker build --rm -t openslide -f Dockerfile .
(output) ... 
Successfully built openslide-python
Installing collected packages: openslide-python
Successfully installed openslide-python-1.1.1
```

Without this change, it was failing because the `setuptools` `Feature` has been removed for `setuptools >= 0.46`:

```
    ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7qfdcpya/openslide-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7qfdcpya/openslide-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-7qfdcpya/openslide-python/pip-egg-info
         cwd: /tmp/pip-install-7qfdcpya/openslide-python/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7qfdcpya/openslide-python/setup.py", line 2, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature'
    ----------------------------------------
```

**Comment by sadeel** [comment]
Will this be pushed to the repo?

**Comment by sadeel** [comment]
Will this be pulled to the repo?

**Comment by sbrugman** [comment]
> Will this be merged to the repo?

@bgilbert @jaharkes

**Comment by robertschweizer** [comment]
Maybe @agoode?

**Comment by frapa** [comment]
We're currently experiencing the issue, because OpenSlides does not install on setuptools >= 46. I think this should be merged ASAP, because the installation is broken.

I'm not a setuptools expert, but the PR looks good IMHO.

**Comment by frapa** [comment]
Thanks for the merge! Is there any plan to release the fixes to pypi?

**Comment by agoode** [comment]
Hi,

Unfortunately, I've never done a pypi release. I don't know if one of the other folks could do it.

**Comment by sbrugman** [comment]
@agoode According to the [PyPi page](https://pypi.org/project/openslide-python/) Benjamin @bgilbert is the only one who could do this currently.

**Comment by keeganwitt** [comment]
Was there any luck in getting in touch with Benjamin?

**Comment by sbrugman** [comment]
> Was there any luck in getting in touch with Benjamin?

I'll have another shot

**Comment by alessiamarcolini** [comment]
Dear everyone, as a gesture of courtesy towards the community, we forked the openslide-python repo and we released it on PyPI. Please note that this is a **temporary workaround** to have openslide-python installable via pip without the setuptools issue.

https://pypi.org/project/openslide-wrapper/1.1.2/

cc @ernestoarbitrio and @nicolebussola

**Comment by bgilbert** [comment]
We'll get a new release out soon.

**Comment by bgilbert** [comment]
Followup PR in #95.

**Pull request merged**
