### PR TITLE
Use more standard __version__ rather than PILLOW_VERSION

### PR DESCRIPTION
**Pull request by hugovk**
They're both the same thing:

https://github.com/python-pillow/Pillow/blob/master/src/PIL/__init__.py

### CODE REVIEW

**Comment by bgilbert** [comment]
Hi, thanks for the PR.  `__version__` is only available in Pillow &ge; 3.4.0.  As the comment says on the preceding line, `PILLOW_VERSION` is available in Pillow &ge; 2.1.0, so this change appears to make the Pillow detection strictly worse.  What problem is this PR intended to solve?

**Comment by bgilbert** [comment]
Thanks for the additional info.  We don't control what version of PIL or Pillow the user has on their system, though.  For example, Ubuntu 14.04 LTS ships Pillow 2.3.0 (hopefully with backported security fixes).

What about

```python
have_optimizations and not (hasattr(Image, 'PILLOW_VERSION') or hasattr(Image, '__version__'))
```

with an appropriate comment?

**Comment by hugovk** [comment]
That looks good. I'll update it.

By the way, `install_requires` means you would control what version the user has: https://stackoverflow.com/a/8161816/724176

```python
install_requires=[ 
     'Pillow >= 3.4', 
 ], 
```

Then when you `pip install openslide-python` it would install at least that version of Pillow.

**Comment by hugovk** [comment]
@bgilbert Hi, any thoughts on this? Thanks!

**Comment by hugovk** [comment]
In Pillow 7.0.0, just released:

> `PILLOW_VERSION` has been removed. Use `__version__` instead.

https://pillow.readthedocs.io/en/stable/deprecations.html#pillow-version-constant

**Comment by hugovk** [comment]
Update:

> It [`PILLOW_VERSION`] was initially removed in Pillow 7.0.0, but brought back in 7.1.0 to give projects more time to upgrade.

https://pillow.readthedocs.io/en/stable/deprecations.html#pillow-version-constant

It'll probably be removed next year. 

Closing this PR because it's over two years old. It's still relevant so I can re-open if there's any interest in merging. Thanks!

**Comment by bgilbert** [comment]
Let's keep this open for now.  Since the constant has been deprecated, we'll need to change this eventually.  Once we revisit which Linux distros still make sense to support, we'll have a better idea whether we still need the compat support or can just drop it.

**Comment by bgilbert** [comment]
9e9f9607f300da8313870605694af57fd5da7cce updates the check to require Pillow &ge; 6.2.0 for #31, and I've switched to `__version__` at the same time.  So this should be fixed now.

Thanks very much for the PR and for your patience.

**Comment by hugovk** [comment]
You're welcome, and thanks!

**Pull request closed without merging**
