### PR TITLE
Fix failure to find libopenslide-0.dll on Windows

### PR DESCRIPTION
**Pull request by simo1427**
In issue #51 I suggested doing this; it was mentioned in issue #23 as well. On every machine, on which I tried installing the library, I had to edit this line.

### CODE REVIEW

**Review by crisz — APPROVED** [review]

**Comment by simo1427** [comment]
Closed by mistake

**Comment by bgilbert** [comment]
`find_library()` should generally not be used at runtime.  Have you tried adding the OpenSlide bin directory to the beginning of your search path?

**Comment by simo1427** [comment]
Yes but to no avail, I even tried doing so in a standalone script with ctypes.cdll.LoadLibrary in it - it still doesn’t work, but find_library continues to find the DLL.

**Comment by crisz** [comment]
After hours (if not days) of research, this is the only fix working

**Comment by jesper-molin** [comment]
I also have this issue and looked how to fix it, Python changed the default behavior in 3.8 to no longer look in PATH when resolving DLL:s on Windows. In the what's new notes, they recommend using [add_dll_directory()](https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew) to resolve this issue or use an absolute path, but then you need to know where to look.

The only reasonable way to search the PATH is to use find_library, if you want to protect against DLL hijacking, the project needs to deliver the win-DLL to a known location and not depending on it being in the PATH. See e.g. for another project's similar problem: https://github.com/beetbox/pyacoustid/issues/54

So I think this is a good patch.

**Comment by bgilbert** [comment]
Okay, yeah, the behavior change in 3.8 seems to explain it.  Does the sample code in https://github.com/openslide/openslide-python/issues/115#issuecomment-799025314 work for you?

> In the what's new notes, they recommend using `add_dll_directory()` to resolve this issue or use an absolute path, but then you need to know where to look.

`add_dll_directory()` seems reasonable.  OpenSlide Python assumes that OpenSlide is provided by some external mechanism, which on Windows is almost certainly under the control of the application.

**Comment by simo1427** [comment]
I pointed the path to the `bin` directory of the `openslide` installation and I can confirm that the quoted code worked.

**Comment by alessiamarcolini** [comment]
Hello maintainers, I was wondering when is this PR going to be merged :) thank you

**Comment by bgilbert** [comment]
@alessiamarcolini On Python 3.8 and later, applications should use the new `os.add_dll_directory()` Python function to add the OpenSlide DLL directory to the search path before importing `openslide`.  We'll update the documentation to include example code, but for now, see https://github.com/openslide/openslide-python/issues/115#issuecomment-799025314.

Since this PR bypasses the new Python API, I'll close.  Thanks for sending!

**Pull request closed without merging**
